name: CI Pipeline

on:
  workflow_dispatch:  # Allows manual triggering of the workflow
    inputs:
        environment:
          description: 'The target environment to deploy'
          required: true
          type: string

jobs:
  build_front:
    name: Build React App
    runs-on: ubuntu-latest
    steps:
      - name: Run task 1
        run: echo Run task 1
      - name: Run task 2
        run: echo Run task 2

  build_backend:
    name: Build .Net services
    runs-on: windows-latest
    steps:
      - name: Run task 1
        run: echo Run task 1
      - name: Azure PowerShell Action
        run: Write-Host "PS task"
        shell: pwsh

  deploy_to_dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    needs: [build_front, build_backend]
    environment: Dev
    steps:
      - name: Run task 1
        run: Write-Host "Deploying to Dev..."
        shell: pwsh
      - name: Run task 2
        run: Write-Host "Deployment complete"
        shell: pwsh

  deploy_to_test:
    name: Deploy to Test
    runs-on: ubuntu-latest
    needs: [build_front, build_backend]
    environment: Test
    steps:
      - name: Run task 1
        run: Write-Host "Deploying to Test..."
        shell: pwsh
      - name: Run task 2
        run: Write-Host "Deployment complete"
        shell: pwsh
        
