name: CI Pipeline

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build_front:
    name: Build React App
    runs-on: ubuntu-latest
    steps:
      - name: Run task 1
        run: echo Run task 1
      - name: Run task 2
        run: echo Run task 2

  build_backend:
    name: Build .Net services
    runs-on: ubuntu-latest
    steps:
      - name: Run task 1
        run: echo Run task 1

  deploy_to_dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    needs: [build_front, build_backend]
    environment: Dev  # Specifies the environment with protection rules
    steps:
      - name: Run task 1
        run: echo Deploying to Dev...
      - name: Run task 2
        run: echo Deployment complete

  deploy_to_test:
    name: Deploy to Test
    runs-on: ubuntu-latest
    needs: [build_front, build_backend]
    environment: Test  # Specifies the environment with protection rules
    steps:
      - name: Run task 1
        run: echo Deploying to Test...
      - name: Run task 2
        run: echo Deployment complete
